DIR=gst-libav
LOC=-b 1.18 https://gitlab.freedesktop.org/gstreamer

include $(TOPDIR)/scripts/uixenv.mk

MICB_DEPENDS = intl iconv alsa gstreamer-1.0 glib-2.0 libavdevice

include $(shell pwd)/../gstreamer.mk

