#!/bin/sh

##
## This is called from meson !! 
## 
## Example) 
## 
## --modversion   :  `/usr/bin/pkg-config --modversion glib-2.0`
## --cflags       :  `/usr/bin/pkg-config --cflags glib-2.0` 
## --libs         :  `/usr/bin/pkg-config --libs glib-2.0` 
##

NATIVE_PKG_CONFIG=/usr/bin/pkg-config

## current folder 
curpwd=$PWD

## objects 
obj=$2

## check this is found from installed packages...
found="`find $INSTALLDIR $EXTINSTDIR $UIXINSTDIR -name \"$obj*.pc\"`"

rc=0

case "$1" in
	"--modversion")
		echo `$NATIVE_PKG_CONFIG --modversion $obj`
		;;
	"--cflags")
		if [ -z "$found" ]; then 
			$NATIVE_PKG_CONFIG --cflags $obj
			rc=$?
		else
			##
			## We do not processing .pc file. This process was already done. 
			## We can simply print out include CFLAGS file..
			##
			echo `cat $curpwd/../flags.incs | xargs -n 1 | sort -u | xargs`
		fi
		;;
	"--libs")
		if [ -z "$found" ]; then 
			$NATIVE_PKG_CONFIG --libs $obj
			rc=$?
		else
			##
			## We do not processing .pc file. This process was already done. 
			## We can simply print out library CFLAGS file..
			##
			echo `cat $curpwd/../flags.libs | xargs -n 1 | sort -u | xargs`
		fi
		;;
	*)
		$NATIVE_PKG_CONFIG $@
		rc=$?
		;;
esac 

return $rc
